# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 19:30
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
